[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
tugn = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@"]

mine = ["bookmark", "list", "-r", "mine()"]

udiff = ["diff", "--config", "ui.diff-formatter=:color-words"]
diff-summary = ["diff", "--summary", "--no-pager"]
diff-files = ["diff", "--name-only", "--no-pager"]
idiff = ["diff", "--tool", "difft-inline"]

l = ["log", "-r", "stack()"]
la = ["log", "-r", "all()"]
ll = ["log", "-T", "builtin_log_detailed"]
lr = ["log", "-r", "remote_bookmarks()"]
o = ["log", "-r", "open()"]

nt = ["new", "trunk()"]
retrunk = ["rebase", "-d", "trunk()"] # rebase the current branch onto the trunk.

# git commands
f = ["git", "fetch"]
p = ["git", "push"]
pc = ["git", "push", "--change", "@-"] # push current cahnges and auto naming the bookmark

oplog = ["op", "log"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"fork_history(to, from)" = "fork_point(to | from)..@"
"stack()" = "stack(@)"
"stack(x)" = "ancestors(reachable(x, mutable()), 2)" # your current branch, root to tip
"open()" = "trunk()..mine() & mutable()"             # everything you haven't landed
"wip()" = "open() & ~empty()"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
diff-formatter = ["difft", "--color=always", "--width=$width", "$left", "$right"]
merge-editor = "nvimdiff3"

[merge-tools.nvimdiff3]
program = "nvim"
merge-args = ["-d", "$output", "-M", "$left", "$base", "$right", "-c", "wincmd J", "-c", "set modifiable", "-c", "set write"]
merge-tool-edits-conflict-markers = true

[merge-tools.difft-inline]
program = "difft"
diff-args = ["--color=always", "--display=inline", "--width=$width", "$left", "$right"]

[lazyjj]
highlight-color = "black"
