font_family JetbrainsMono Nerd Font
italic_font family="ComicCodeLigatures Nerd Font" style=Italic
bold_italic_font auto
font_size 10

remember_window_size no
initial_window_width 150c
initial_window_height 45c
window_padding_width 10
hide_window_decorations no
background_opacity 1
inactive_text_alpha 0.75

copy_on_select clipboard
mouse_hide_wait 3

shell_integration no-cursor
shell fish

cursor_shape block
cursor_blink_interval 0.5

active_border_color #6e6a86
inactive_border_color #6e6a86

# Vague
foreground #cdcdcd
background #141415
cursor #cdcdcd
cursor_text_color #141415
selection_foreground #e0e0e4
selection_background #3e3e42

color0 #252530
color1 #d8647e
color2 #7fa563
color3 #f3be7c
color4 #6e94b2
color5 #bb9dbd
color6 #aeaed1
color7 #cdcdcd
color8 #606079
color9 #e08398
color10 #99b782
color11 #f5cb96
color12 #8ba9c1
color13 #c9b1ca
color14 #bebeda
color15 #d7d7d7

map shift+enter send_text all \x1b\r
map alt+backspace send_text all \x1b\x7f
