---
gui:
  nerdFontsVersion: "3"
  showIcons: true

  theme:
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - default
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
    cherryPickedCommitBgColor:
      - black
    cherryPickedCommitFgColor:
      - magenta
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
    searchingActiveBorderColor:
      - yellow

  authorColors:
    "*": cyan

  showFileTree: true
  keybinding:
    universal:
      quit: q
